#pragma once

#include "../../Application.h"

#include <mutex>

#include <Containers/SmallVector.h>

struct android_app;
struct AInputEvent;

namespace nCine
{
	/**
		@brief Main entry point and handler for Android applications
		
		Specializes @ref Application for the Android platform, wiring the engine to the
		`android_native_app_glue` lifecycle and dispatching the platform commands it receives.
	*/
	class AndroidApplication : public Application
	{
	public:
		/**
		 * @brief Entry point method to be called in the `android_main()` function
		 *
		 * @param state					Native application state provided by the glue layer
		 * @param createAppEventHandler	Factory delegate that creates the application's event handler
		 */
		static void Run(struct android_app* state, CreateAppEventHandlerDelegate createAppEventHandler);

		/**
		 * @brief Processes an Android application lifecycle command
		 *
		 * @param state	Native application state provided by the glue layer
		 * @param cmd	One of the `APP_CMD_*` commands dispatched by the glue layer
		 */
		static void ProcessCommand(struct android_app* state, std::int32_t cmd);

		/** @brief Returns `true` if the application has already called @ref Init() */
		inline bool IsInitialized() const {
			return _isInitialized;
		}

		/** @brief Returns `true` if the main screen is round */
		inline bool IsScreenRound() const {
			return _isScreenRound;
		}

		bool OpenUrl(StringView url) override;

		/** @brief Handles invocation of the system Back gesture */
		void HandleBackInvoked();

		/**
		 * @brief Handles the intent sent to the application activity
		 *
		 * @param action	Intent action string
		 * @param uri		Intent data URI
		 */
		void HandleIntent(StringView action, StringView uri);

		/**
		 * @brief Handles changes of content bounds
		 *
		 * @param bounds	New content bounds, accounting for insets such as display cutouts
		 */
		void HandleContentBoundsChanged(Recti bounds);

		/**
		 * @brief Handles a Unicode character entered on the screen keyboard
		 *
		 * @param codePoint	Entered Unicode code point
		 *
		 * Can be called from the Java UI thread, the event is queued and dispatched on the main thread.
		 */
		void HandleTextInput(char32_t codePoint);

		/**
		 * @brief Handles a key event generated by the screen keyboard
		 *
		 * @param pressed	`true` if the key was pressed, `false` if it was released
		 * @param keyCode	Android key code of the key
		 *
		 * Can be called from the Java UI thread, the event is queued and dispatched on the main thread.
		 */
		void HandleKeyEvent(bool pressed, std::int32_t keyCode);

		bool CanShowScreenKeyboard() override;
		bool IsScreenKeyboardVisible() override;
		bool ToggleScreenKeyboard() override;
		bool ShowScreenKeyboard() override;
		bool HideScreenKeyboard() override;
		void Vibrate(std::int32_t milliseconds) override;
		void ShowStatusBar() override;
		void HideStatusBar() override;

	private:
		/** @brief Input event received from the Java UI thread and waiting to be dispatched on the main thread */
		struct DeferredInputEvent
		{
			/** @brief Android key code, or `0` if the event carries a Unicode character instead */
			std::int32_t KeyCode;
			/** @brief Entered Unicode code point, valid only if @ref KeyCode is `0` */
			char32_t CodePoint;
			/** @brief `true` if the key was pressed, `false` if it was released */
			bool Pressed;
		};

		bool _isInitialized;
		bool _isBackInvoked;
		bool _isScreenRound;
		bool _canShowScreenKeyboard;

		struct android_app* _state;
		CreateAppEventHandlerDelegate _createAppEventHandler;

		// `nCine::Mutex` is not available when the engine is built without thread support
		std::mutex _deferredInputLock;
		SmallVector<DeferredInputEvent, 0> _deferredInput;

		/** @brief Dispatches all input events received from the Java UI thread since the last call */
		void ProcessDeferredInput();

		void PreInit();
		/** @brief Must be called at the beginning to initialize the application */
		void Init();
		/** @brief Must be called before exiting to shut down the application */
		void Shutdown();

		AndroidApplication();
		~AndroidApplication();

		AndroidApplication(const AndroidApplication&) = delete;
		AndroidApplication& operator=(const AndroidApplication&) = delete;

		/** @brief Returns the singleton reference to the Android application */
		static AndroidApplication& theAndroidApplication() {
			return static_cast<AndroidApplication&>(theApplication());
		}

		friend Application& theApplication();
	};

	/** @brief Returns the application instance */
	Application& theApplication();

}
