#include "Emit.h"

namespace ShaderCompiler
{
	namespace
	{
		/** C++ names of the UniformType enumerators, indexed by GlslType */
		const char* EnumName(GlslType type)
		{
			switch (type) {
				case GlslType::Float: return "Float";
				case GlslType::Int: return "Int";
				case GlslType::UInt: return "UInt";
				case GlslType::Bool: return "Bool";
				case GlslType::Vec2: return "Vec2";
				case GlslType::Vec3: return "Vec3";
				case GlslType::Vec4: return "Vec4";
				case GlslType::IVec2: return "IVec2";
				case GlslType::IVec3: return "IVec3";
				case GlslType::IVec4: return "IVec4";
				case GlslType::UVec2: return "UVec2";
				case GlslType::UVec3: return "UVec3";
				case GlslType::UVec4: return "UVec4";
				case GlslType::BVec2: return "BVec2";
				case GlslType::BVec3: return "BVec3";
				case GlslType::BVec4: return "BVec4";
				case GlslType::Mat2: return "Mat2";
				case GlslType::Mat3: return "Mat3";
				case GlslType::Mat4: return "Mat4";
				case GlslType::Sampler2D: return "Sampler2D";
				case GlslType::Sampler3D: return "Sampler3D";
				case GlslType::SamplerCube: return "SamplerCube";
				case GlslType::Struct: return "Struct";
			}
			return "Float";
		}

		std::string ArraySizeExpr(std::uint32_t arraySize, bool symbolic)
		{
			if (symbolic) {
				return "ShaderCompiler::SymbolicArraySize";
			}
			return std::to_string(arraySize);
		}

		std::string ArraySuffix(std::uint32_t arraySize, bool symbolic)
		{
			if (symbolic) {
				return "[*]";
			}
			if (arraySize != 0) {
				return "[" + std::to_string(arraySize) + "]";
			}
			return std::string();
		}

		/**
			Common reflection types for the standalone "ShaderCompilerTypes.h" header, which every
			generated header includes. Kept in the fixed "ShaderCompiler" namespace (not the -n
			namespace) so that generated headers with different data namespaces share one set.
		*/
		const char ReflectionTypes[] = R"TYPES(#ifndef SHADERCOMPILER_REFLECTION_TYPES
#define SHADERCOMPILER_REFLECTION_TYPES

namespace ShaderCompiler
{
	// Scalar/vector/matrix/opaque type of a uniform, block member or vertex attribute
	enum class UniformType : std::uint8_t
	{
		Float, Int, UInt, Bool,
		Vec2, Vec3, Vec4,
		IVec2, IVec3, IVec4,
		UVec2, UVec3, UVec4,
		BVec2, BVec3, BVec4,
		Mat2, Mat3, Mat4,
		Sampler2D, Sampler3D, SamplerCube,
		Struct
	};

	// ArraySize value marking an array sized by the symbolic BATCH_SIZE constant
	inline constexpr std::uint16_t SymbolicArraySize = 0xFFFFu;

	// Loose (non-block, non-sampler) uniform
	struct Uniform
	{
		const char* Name;
		UniformType Type;
		std::uint16_t ArraySize;		// 0 = not an array
	};

	// Member of a std140 uniform block
	struct BlockMember
	{
		const char* Name;
		UniformType Type;
		std::uint16_t ArraySize;		// 0 = not an array, SymbolicArraySize = BATCH_SIZE-sized
		std::uint32_t Offset;			// std140 offset from the start of the block
	};

	// std140 uniform block
	struct UniformBlock
	{
		const char* Name;
		std::uint32_t BaseSize;			// std140 size covering everything except symbolic arrays
		std::uint32_t InstanceStride;	// std140 element stride of the BATCH_SIZE-sized array (0 if none);
										// the runtime computes the batch size as maxUniformBlockSize / InstanceStride
		std::size_t MemberCount;
		const BlockMember* Members;
	};

	// Sampler uniform with its assigned texture unit
	struct TextureBinding
	{
		const char* Name;
		std::int32_t Unit;				// -1 = not assigned
	};

	// Vertex attribute
	struct Attribute
	{
		const char* Name;
		UniformType Type;
		std::int32_t Location;			// -1 = unspecified
	};

	// "render_mode" flags carried on Program (bitmask; 0 when no render_mode is declared)
	enum class RenderMode : std::uint32_t
	{
		BlendMix = 0x01,
		BlendAdd = 0x02,
		BlendSub = 0x04,
		BlendMul = 0x08,
		BlendPremulAlpha = 0x10,
		Unshaded = 0x20
	};

	// One compiled variant of a program
	struct ProgramVariant
	{
		const char* Name;				// "" for the base variant, otherwise the variant name
		const char* Defines;			// "" or the name of the baked "#define <NAME> (1)"
		const char* VsSource;
		const char* FsSource;
		std::size_t UniformCount;
		const Uniform* Uniforms;
		std::size_t BlockCount;
		const UniformBlock* Blocks;
		std::size_t TextureCount;
		const TextureBinding* Textures;
		std::size_t AttributeCount;
		const Attribute* Attributes;
	};

	// A shader program with all of its variants (Variants[0] is always the base variant, whose Name is "")
	struct Program
	{
		const char* Name;
		std::uint32_t RenderModes;		// Bitmask of RenderMode flags (0 when no render_mode is declared)
		std::size_t VariantCount;
		const ProgramVariant* Variants;
	};
}

#endif
)TYPES";
	}

	std::string Emitter::BuildTypesHeader()
	{
		std::string output;
		output += "// Generated by ShaderCompiler. Do not edit manually.\n";
		output += "// Shared reflection types included by every generated shader artifact header.\n";
		output += "#pragma once\n";
		output += "\n";
		output += "#include <cstddef>\n";
		output += "#include <cstdint>\n";
		output += "\n";
		output += ReflectionTypes;
		return output;
	}

	namespace
	{
		/** Emits one program (per-variant sources, reflection arrays, variant list and Program descriptor) into @p output */
		bool EmitProgram(const ShaderDocument& document, const std::vector<VariantReflection>& variants,
			std::string& output, Diagnostic& diag)
		{
			const std::string& program = document.ProgramName;

			for (const VariantReflection& v : variants) {
				// The unnamed base variant carries no infix ("Lighting_Vs"), named variants keep theirs ("Tinted_USE_PALETTE_Vs")
				const std::string prefix = (v.Name.empty() ? program : program + "_" + v.Name);
				const StageReflection& r = v.Reflection;

				for (std::int32_t stage = 0; stage < 2; stage++) {
					bool vertexStage = (stage == 0);
					std::string source = ShaderParser::BuildStageSource(document, vertexStage, v.Define);
					if (source.find(")__SHDR__\"") != std::string::npos) {
						diag.Message = "shader source contains the raw string terminator sequence )__SHDR__\"";
						diag.Line = 1;
						return false;
					}
					output += "\tinline constexpr char " + prefix + (vertexStage ? "_Vs" : "_Fs") + "[] =\n";
					output += "R\"__SHDR__(";
					output += source;
					output += ")__SHDR__\";\n";
					output += "\n";
				}

				if (!r.Uniforms.empty()) {
					output += "\tinline constexpr ShaderCompiler::Uniform " + prefix + "_Uniforms[] = {\n";
					for (const UniformInfo& u : r.Uniforms) {
						output += "\t\t{ \"" + u.Name + "\", ShaderCompiler::UniformType::" + EnumName(u.Type) + ", " + ArraySizeExpr(u.ArraySize, false) + " },\n";
					}
					output += "\t};\n";
					output += "\n";
				}

				for (std::size_t i = 0; i < r.Blocks.size(); i++) {
					const BlockInfo& block = r.Blocks[i];
					output += "\tinline constexpr ShaderCompiler::BlockMember " + prefix + "_Block" + std::to_string(i) + "_Members[] = {\n";
					for (const MemberInfo& m : block.Members) {
						output += "\t\t{ \"" + m.Name + "\", ShaderCompiler::UniformType::" + EnumName(m.Type) + ", " +
							ArraySizeExpr(m.ArraySize, m.SymbolicArray) + ", " + std::to_string(m.Offset) + " },\n";
					}
					output += "\t};\n";
					output += "\n";
				}
				if (!r.Blocks.empty()) {
					output += "\tinline constexpr ShaderCompiler::UniformBlock " + prefix + "_Blocks[] = {\n";
					for (std::size_t i = 0; i < r.Blocks.size(); i++) {
						const BlockInfo& block = r.Blocks[i];
						output += "\t\t{ \"" + block.Name + "\", " + std::to_string(block.BaseSize) + ", " +
							std::to_string(block.InstanceStride) + ", " + std::to_string(block.Members.size()) + ", " +
							prefix + "_Block" + std::to_string(i) + "_Members },\n";
					}
					output += "\t};\n";
					output += "\n";
				}

				if (!r.Textures.empty()) {
					output += "\tinline constexpr ShaderCompiler::TextureBinding " + prefix + "_Textures[] = {\n";
					for (const TextureInfo& t : r.Textures) {
						output += "\t\t{ \"" + t.Name + "\", " + std::to_string(t.Unit) + " },\n";
					}
					output += "\t};\n";
					output += "\n";
				}

				if (!r.Attributes.empty()) {
					output += "\tinline constexpr ShaderCompiler::Attribute " + prefix + "_Attributes[] = {\n";
					for (const AttributeInfo& a : r.Attributes) {
						output += "\t\t{ \"" + a.Name + "\", ShaderCompiler::UniformType::" + EnumName(a.Type) + ", " + std::to_string(a.Location) + " },\n";
					}
					output += "\t};\n";
					output += "\n";
				}
			}

			output += "\tinline constexpr ShaderCompiler::ProgramVariant " + program + "_Variants[] = {\n";
			for (const VariantReflection& v : variants) {
				const std::string prefix = (v.Name.empty() ? program : program + "_" + v.Name);
				const StageReflection& r = v.Reflection;
				output += "\t\t{ \"" + v.Name + "\", \"" + v.Define + "\", " + prefix + "_Vs, " + prefix + "_Fs,\n";
				output += "\t\t\t" + std::to_string(r.Uniforms.size()) + ", " + (r.Uniforms.empty() ? std::string("nullptr") : prefix + "_Uniforms") + ", ";
				output += std::to_string(r.Blocks.size()) + ", " + (r.Blocks.empty() ? std::string("nullptr") : prefix + "_Blocks") + ", ";
				output += std::to_string(r.Textures.size()) + ", " + (r.Textures.empty() ? std::string("nullptr") : prefix + "_Textures") + ", ";
				output += std::to_string(r.Attributes.size()) + ", " + (r.Attributes.empty() ? std::string("nullptr") : prefix + "_Attributes") + " },\n";
			}
			output += "\t};\n";
			output += "\n";
			output += "\tinline constexpr ShaderCompiler::Program " + program + " = { \"" + program + "\", " +
				std::to_string(document.RenderModes) + ", " + std::to_string(variants.size()) + ", " + program + "_Variants };\n";
			return true;
		}
	}

	bool Emitter::EmitHeader(const std::vector<ProgramReflection>& programs,
		const std::string& ns, const std::string& inputFileName, std::string& output, Diagnostic& diag)
	{
		// Only the file name is embedded, so generated headers don't differ between machines
		std::string inputName = inputFileName;
		std::size_t lastSeparator = inputName.find_last_of("/\\");
		if (lastSeparator != std::string::npos) {
			inputName = inputName.substr(lastSeparator + 1);
		}

		output.clear();
		output += "// Generated by ShaderCompiler from " + inputName + ". Do not edit manually.\n";
		output += "#pragma once\n";
		output += "\n";
		output += "#include \"ShaderCompilerTypes.h\"\n";
		output += "\n";
		output += "namespace " + ns + "\n";
		output += "{\n";

		for (std::size_t i = 0; i < programs.size(); i++) {
			if (i != 0) {
				output += "\n";
			}
			if (!EmitProgram(*programs[i].Document, programs[i].Variants, output, diag)) {
				return false;
			}
		}

		output += "}\n";
		return true;
	}

	std::string Emitter::BuildCheckDump(const ShaderDocument& document, const std::vector<VariantReflection>& variants)
	{
		std::string out;
		out += "program " + document.ProgramName + "\n";
		if (document.RenderModes != 0) {
			static const struct { std::uint32_t Bit; const char* Name; } RenderModeNames[] = {
				{ RenderModeBlendMix, "blend_mix" }, { RenderModeBlendAdd, "blend_add" },
				{ RenderModeBlendSub, "blend_sub" }, { RenderModeBlendMul, "blend_mul" },
				{ RenderModeBlendPremulAlpha, "blend_premul_alpha" }, { RenderModeUnshaded, "unshaded" }
			};
			out += "render_mode";
			bool first = true;
			for (const auto& mode : RenderModeNames) {
				if ((document.RenderModes & mode.Bit) != 0) {
					out += (first ? " " : ", ");
					out += mode.Name;
					first = false;
				}
			}
			out += "\n";
		}
		for (const VariantReflection& v : variants) {
			const StageReflection& r = v.Reflection;
			out += (v.Name.empty() ? "variant (base)\n" : "variant " + v.Name + "\n");
			if (!v.Define.empty()) {
				out += "  define " + v.Define + "\n";
			}
			for (const StructInfo& s : r.Structs) {
				out += "  struct " + s.Name + " size=" + std::to_string(s.Size) + " align=" + std::to_string(s.Align) + "\n";
				for (const MemberInfo& f : s.Fields) {
					out += "    field " + f.TypeName + " " + f.Name + ArraySuffix(f.ArraySize, f.SymbolicArray) +
						" offset=" + std::to_string(f.Offset) + "\n";
				}
			}
			for (const UniformInfo& u : r.Uniforms) {
				out += "  uniform " + u.TypeName + " " + u.Name + ArraySuffix(u.ArraySize, false) + "\n";
			}
			for (const BlockInfo& b : r.Blocks) {
				out += "  block " + b.Name + " baseSize=" + std::to_string(b.BaseSize) +
					" instanceStride=" + std::to_string(b.InstanceStride) + "\n";
				for (const MemberInfo& m : b.Members) {
					out += "    member " + m.TypeName + " " + m.Name + ArraySuffix(m.ArraySize, m.SymbolicArray) +
						" offset=" + std::to_string(m.Offset) + "\n";
				}
			}
			for (const TextureInfo& t : r.Textures) {
				out += "  texture " + t.Name + " unit=" + std::to_string(t.Unit) + "\n";
			}
			for (const AttributeInfo& a : r.Attributes) {
				out += "  attribute " + a.TypeName + " " + a.Name + " location=" + std::to_string(a.Location) + "\n";
			}
		}
		return out;
	}
}
