# Runs ShaderCompiler.exe over every Sources/Shaders/*.shader and emits the generated C++ headers
# into Sources/Shaders/Generated/<Name>.h.
#
# Namespace convention:
#   Default*.shader (nCine default shader programs) -> nCine::ShadersGen
#   everything else (Jazz2 PrecompiledShader programs) -> Jazz2::ShadersGen
#
# Fails with a non-zero exit code if any shader fails to process.

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$shadersDir = Join-Path (Split-Path -Parent $scriptDir) 'Shaders'
$outDir = Join-Path $shadersDir 'Generated'
$tool = Join-Path $scriptDir 'x64\Release\ShaderCompiler.exe'

if (-not (Test-Path $tool)) {
    Write-Host "error: ShaderCompiler.exe not found at '$tool' - build Sources/ShaderCompiler first"
    exit 1
}
if (-not (Test-Path $shadersDir)) {
    Write-Host "error: Shader directory not found at '$shadersDir'"
    exit 1
}

New-Item -ItemType Directory -Force $outDir | Out-Null

# Shared reflection types included by every generated header (and by engine code that consumes reflection)
& $tool --emit-types (Join-Path $outDir 'ShaderCompilerTypes.h')
if ($LASTEXITCODE -ne 0) {
    Write-Host "error: failed to emit ShaderCompilerTypes.h"
    exit 1
}

$shaders = @(Get-ChildItem (Join-Path $shadersDir '*.shader') | Sort-Object Name)
if ($shaders.Count -eq 0) {
    Write-Host "error: No .shader files found in '$shadersDir'"
    exit 1
}

$failed = 0
foreach ($shader in $shaders) {
    $name = $shader.BaseName
    if ($name -like 'Default*') {
        $ns = 'nCine::ShadersGen'
    } else {
        $ns = 'Jazz2::ShadersGen'
    }
    $outPath = Join-Path $outDir ($name + '.h')

    & $tool $shader.FullName -o $outPath -n $ns
    if ($LASTEXITCODE -ne 0) {
        Write-Host "error: '$($shader.Name)' failed with exit code $LASTEXITCODE"
        $failed++
    } else {
        Write-Host "ok: $($shader.Name) -> Generated\$name.h [$ns]"
    }
}

if ($failed -gt 0) {
    Write-Host "error: $failed of $($shaders.Count) shader(s) failed"
    exit 1
}

# Emit the umbrella header including every generated program plus per-namespace index arrays,
# so runtime code has a single include and can enumerate the programs.
# A canvas_item file with a "batched" directive carries TWO programs in one header, so the
# program symbols come from the directives, not from the file names.
function Get-ProgramNames($shaderFile) {
    $names = @()
    foreach ($line in Get-Content $shaderFile.FullName) {
        if ($line -cmatch '^\s*(?:program|batched)\s+(\w+)\s*;') {
            $names += $Matches[1]
        }
    }
    return $names
}

$jazz2Names = @($shaders | Where-Object { $_.BaseName -notlike 'Default*' } | ForEach-Object { Get-ProgramNames $_ })
$ncineNames = @($shaders | Where-Object { $_.BaseName -like 'Default*' } | ForEach-Object { Get-ProgramNames $_ })

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Generated by GenerateAll.ps1. Do not edit manually.')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
foreach ($name in ($shaders | ForEach-Object { $_.BaseName } | Sort-Object)) {
    [void]$sb.AppendLine("#include `"$name.h`"")
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace Jazz2::ShadersGen')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine("`t// All generated Jazz2 shader programs, sorted by name")
[void]$sb.AppendLine("`tinline constexpr const ShaderCompiler::Program* AllPrograms[] = {")
foreach ($name in $jazz2Names) {
    [void]$sb.AppendLine("`t`t&$name,")
}
[void]$sb.AppendLine("`t};")
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace nCine::ShadersGen')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine("`t// All generated nCine default shader programs, sorted by name")
[void]$sb.AppendLine("`tinline constexpr const ShaderCompiler::Program* AllPrograms[] = {")
foreach ($name in $ncineNames) {
    [void]$sb.AppendLine("`t`t&$name,")
}
[void]$sb.AppendLine("`t};")
[void]$sb.AppendLine('}')

$umbrellaPath = Join-Path $outDir 'ShadersGen.h'
[System.IO.File]::WriteAllText($umbrellaPath, $sb.ToString().Replace("`r`n", "`n").Replace("`n", "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "ok: umbrella -> Generated\ShadersGen.h ($($jazz2Names.Count) Jazz2 + $($ncineNames.Count) nCine programs)"

Write-Host "All $($shaders.Count) shaders generated successfully."
exit 0
