# Turns PS2SDK's IOP modules into a C++ source of byte arrays, so they can be handed to
# SifExecModuleBuffer() instead of being read from a storage device the module is itself the only way to
# reach - see Sources/nCine/Backends/Ps2/Ps2Modules.h for why that matters on this console.
#
# Runs at configure time rather than as a build rule: the modules come from the installed PS2SDK and only
# change when the toolchain does, and generating them here means the result is a plain source file in the
# SOURCES list with no custom-command ordering to get wrong.

# Appends one module to `outContent` as `alignas(64) const std::uint8_t <symbol>[] = { ... };` plus its size.
function(ncine_internal_ps2_embed_one_module symbol path outContent)
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "Cannot embed PS2 IOP module \"${path}\" - it is not in the installed PS2SDK")
	endif()

	file(READ "${path}" _hex HEX)
	string(LENGTH "${_hex}" _hexLength)
	math(EXPR _byteCount "${_hexLength} / 2")

	# Two hex digits become one "0x..," literal, and a line break every 16 bytes keeps the generated file
	# something a compiler (and a person looking for a truncated module) can work through
	string(REGEX REPLACE "(................................)" "\\1\n\t\t" _hex "${_hex}")
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _hex "${_hex}")

	set(${outContent} "${${outContent}}
	// ${path} (${_byteCount} bytes)
	alignas(64) const std::uint8_t ${symbol}[] = {
\t\t${_hex}
	};
	const std::uint32_t ${symbol}Size = ${_byteCount};
" PARENT_SCOPE)
endfunction()

# Generates the embedded-module source into the build tree and returns its path in `outSource`.
# The remaining arguments are "Symbol=file.irx" pairs resolved against "$ENV{PS2SDK}/iop/irx".
function(ncine_ps2_embed_irx_modules outSource)
	set(_irxDir "$ENV{PS2SDK}/iop/irx")
	set(_generatedDir "${CMAKE_BINARY_DIR}/Generated")
	set(_generatedSource "${_generatedDir}/Ps2EmbeddedModules.cpp")
	file(MAKE_DIRECTORY "${_generatedDir}")

	set(_content "// Generated by cmake/ncine_ps2_embed_irx.cmake from the installed PS2SDK. Do not edit manually.

#include \"${CMAKE_SOURCE_DIR}/Sources/nCine/Backends/Ps2/Ps2Modules.h\"

#if defined(WITH_PS2)

namespace nCine::Backends::Ps2Modules
{")

	foreach(_entry IN LISTS ARGN)
		string(REPLACE "=" ";" _parts "${_entry}")
		list(GET _parts 0 _symbol)
		list(GET _parts 1 _file)
		ncine_internal_ps2_embed_one_module("${_symbol}" "${_irxDir}/${_file}" _content)
	endforeach()

	set(_content "${_content}}

#endif
")

	# Only rewritten when it actually differs, so a reconfigure does not rebuild the world
	file(GENERATE OUTPUT "${_generatedSource}" CONTENT "${_content}")
	# file(GENERATE) writes during the generate step, which is after the target is created, so the source
	# has to be declared as produced by the build or CMake refuses to add a file that is not there yet
	set_source_files_properties("${_generatedSource}" PROPERTIES GENERATED TRUE)
	set(${outSource} "${_generatedSource}" PARENT_SCOPE)
endfunction()
